export const FIREBASE_CONNECT_LOADING = "MovieHack.firebase.FIREBASE_CONNECT_LOADING";
export const FIREBASE_CONNECT_SUCCESS = "MovieHack.firebase.FIREBASE_CONNECT_SUCCESS";
export const FIREBASE_CONNECT_FAILURE = "MovieHack.firebase.FIREBASE_CONNECT_FAILURE";

export const FIREBASE_DATA_CHANGED = "MovieHack.firebase.FIREBASE_DATA_CHANGED";
