export const FIREBASE_MOVIES_SAVING = "MovieHack.feed.FIREBASE_MOVIES_SAVING";
export const FIREBASE_MOVIES_SAVED = "MovieHack.feed.FIREBASE_MOVIES_SAVED";
export const FIREBASE_MOVIES_FETCHING = "MovieHack.feed.FIREBASE_MOVIES_FETCHING";
export const FIREBASE_MOVIES_FETCHED = "MovieHack.feed.FIREBASE_MOVIES_FETCHED";
export const FIREBASE_MOVIES_FETCH_FAILED = "MovieHack.feed.FIREBASE_MOVIES_FETCH_FAILED";
