export const FETCH_MOVIE_DETAILS_LOADING = "MovieHack.feed.FETCH_MOVIE_DETAILS_LOADING";
export const FETCH_MOVIE_DETAILS_LOADED = "MovieHack.feed.FETCH_MOVIE_DETAILS_LOADED";
export const FETCH_MOVIE_DETAILS_FAILED = "MovieHack.feed.FETCH_MOVIE_DETAILS_FAILED";
